language: node_js
node_js:
- '0.12'
cache:
  directories:
  - node_modules
addons:
  sauce_connect: true
script:
- gulp test
- gulp protractor
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g bower
- bower install
- npm install -g gulp
# env:
#   global:
#   - secure: Jjtvzj+UIs68HzHh8VN4k9VIL7+79hiskv8L9MkUh0gUWNftTBJiczZ5djucsvKkIjtalYP0rYDQFGTWFtqGuhterd7qS4052LlY0RCsxdTh5mLzF7XW6rMxt0vukof6fZHzxwoqXN8BMyPSobDjrjPJLORcx/ncmJqy5RsgWq6w90xpwlMgep5lTKLTn8pjmEkjAgPoIhQxPU6TtmqR8ri/u9YUS8OYDzeCcxvKIGNYpNBhodME7AVXWo+R4Y2zguXVVI3PNEDRQDbbBMXgkMYV5P98AzyFh+o0AmShSSbXcdrKs6MtceUWWCmGTAJg3vtye1rvFkuBfJHkrZhOYqNbTThfDpfU52e0stlUWNDizddtVQKCr7/WfNd6Wi25E/Y00YV4pcyQ2lzk36pB0gSW3BpXbsV4AROJmq+eUxxtgMcAncRJc/Vc1kBySNisa+jMnWxCZkgPl3DdhE+3KzA3tcZIxrUOLF2ecpBo1gp9AKy5drBZsz4hhTB5I56cjQd4L4XV3BgEyfL6SqIezq5rNtFi5mPB7Gv2PeWiTC0gLWelic5ptcmdmsyhdwVSJPmuNBi7ddgkui2Wo36SxV1CRl7oLVWup937WGJQLPq3Wbeqbbmf2khkskep/m0oiE2Yw1plwuEAmlFH0+aKFP1NzZwvvYgKeTDxnSqqijQ=
#   - secure: qhFgQHAu57Y5BaTAL4gZP+fhEgkXt2n9NpKAmZsqkOvwEtWsbOdm8t5lIRPFPlMr7fUw0uoQTEeULIQsGFX1LV2sCK2A+azvrXqR88iRvzFwFcSvg0CcGJR/sZ0lwU+B/UlEOxgOniSMzqehoo9NdWpRStqlnfxDNiZ16YlimRdvAjBGlbULfe5WemJuuT+BQnN9uEPz1M/72dFYC1diJ8dae3AZG7aa2zvNnsP5Tp8QVpl1IoQqqYSteKlJVZVcMCQ+I/yaGV8VYfTWU25F3RR4+aajraZSzryWoeJ07xz5TKfqjXlynbdYQxhkMRZGKf84DPAhmFrb2oJ1dMQd/p8p7F+NDbaCyM0BQB3o8gY96UdSgYwVqdEfypPU6cMfmXfTMwOfhNdMYX4sKlmRmH59OWaD7j7coZGSzXMqIlNtAARV1Zj0N4XaBAHnTaWHe8v+2FFlx4As7oeynRjrVPixLGzqjxnUbTPqedFST4YuwRYceSET2XSTsC0J1PEhielL0HorMZ+mYRXkx9Ae+jEdjHLWVXWwCvpTMzXb2k/3WscmZZVEEyJ5sOiu1NFFZah8Obt3aDwyVCf3qzCQC8SKe+9emmyyHWiDQqdc22EV93h7jZIHtz6FPeXNvUvjigFkL7GIWvF/SEJD3aXLwWm2njFPwdSOl7zz2hX6mzE=
