language: node_js
node_js:
- '0.12'
cache:
  directories:
  - node_modules
script:
- gulp test
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g bower
- bower install
- npm install -g gulp
deploy:
  provider: heroku
  app:
    master: visualfda
    staging: stagingvisualfda
  api_key:
    secure: BLVCGE6wvfGCY6Oh49GQfJrywq2NEDG4hchX7L3xC+1HX3tVvGbbn/6sfgiDqaLvsUqV+13WHpJgts5u5n1FJ797iedjgzuUJ0kRyZPXy3Gq3+KLa79DTeYKJYG1cNGmyXx3Sj2gG3gW8oiluaB8fFAqEonJwHOusD9tRs0Acm1qPALtb5RP85COqOI5yVaTx+4jBGo5PGvW+w2bd40M8hK4SDuFmnV5BTvCPdSj02RtwwEw72FpexEe0gj67EQ7r5oMpezyL8z6Kq+aJjXUC7m+JwsSgpk5Lt2jJpx/WeljF868YdfkDzuDdNqZ58JrBgwAMPBvc/35+SOSUTpXHPburEOPss59e34L3iEO0gAlITdcZTJ3XKUMEqqD4zjR0cKYJByPKZeZw4OBdbXqopQoEz7eTiTsgZhVc5AGW3Y3JcsV97JmLsRrvpVUMfs2U3ZPsOPvFfYH3QkMRrDnDdLZlDXsMnsa1MmQ4GDQMRlpgeBapVwfH+l96jaPxm7bCuKmr1qfPz8my+cAdv/COUNryGKIiQhTeSBQOEDwr9kfRW20C55AwXDFqEmA4d1ZKdrcNSZdSnILjcmPKpeUwLp8YXwbo4KpQUcCTRoQR3yjGCt2MlPr7DoGzdGv15epwP/9PWgfPVterho1Oo4tUcyMp0pjLaQiAGrg6ON6dFY=
