language: node_js
node_js:
- '0.12'
cache:
  directories:
  - node_modules
script:
- gulp test
- gulp protractor
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g bower
- bower install
- npm install -g gulp
- curl https://raw.githubusercontent.com/cepinos/FDA-app-prototype/master/scripts/sauce_connect_setup.sh | bash
env:
  global:
  - secure: vQQgD58xfSzMvEkHbguKCe4fmOE/mGxfJqwQFlweuPV43o1MCZ3J/QVjEzFIyKMoQhPS/x2tcFVo9VKZJB/bRSib2xINCJD8FeR8ikHVTHKFN5G0K6Ifv4rFdykqf/HDnsC+E+fB1jkLlmNC/qISIV2ne2hxFJx2qY0fh0KBGqr3wprDme9vWCoWUm0Rnri9hMEMA3zelu5mq8cheHNvSZWeyMRq2DTxkBAsOcF43rQthbHpuX3vc1+b68MtosFhEkCnzgeAi+0qggBSvVbJBh1z/WKkk1VP7t9ATq9zVKk0+8dhBapSPc/k/V243JHsz7w1pnA2YEynCRABYRe7K/ZzWE5675b5q2LsU9Rul7jITJD0HWpJrCfKY7HdO3qpFWwRjNRfkUk2HHmny35ultTmOEqTGhfvnGV+KidqM6EhthmVnyVmMk66sdW09uyuzkvwr285ipabieQX9ySVwsNagEg5r5R6XozvQ7VOxAFNxEQVmB1EgWFnMgqedwz0q1v9INafT3dzOuuTH/nX4VFH5fy6BQ27YdBmiRp1Qbmt7+pAoEU568g8seqmoRb60YzB6/TAXbO7rozW77SdLRLCxr3GIetlaaMSlQK7njsPK7vqjVkZr6krVDRt6i6lA1N6OxfLYUisfakW6sr+W/hMNe2lqO/3mDwubI75l4E=
  - secure: LwUKFJ5Ag3d/OHcSUNDs4rnuMGJn4uA/SqvR86O+rSzj4VovY08yvRhGk1YVV5toD+EwLEAIsMpf90YfEj9N0YgMsPurGMWyMgZxUtVClw+1TGQbyIhpc0A58TscQaP+V5lIAXdP3ENdvfXoAROPCuq6i/dy9FxBSjK41PqZre3C7h6DQgNt/UlTwaQzkCw0bEhZwGZn3UFHGl9G3/q6Lr0U1pBvi3EBa9X6sW1dnCfnBsTyPPepVdRaSs0lUYr0eoF4fkAgxlAJuj+HX6k3YXulEz452KoSPBTmox7AWpKUPXU6r3p6W/k+mNYH8J0q0jM9F77PQ33bHxM9FBekoIIpd47lDq2cv5yV+J76441hNB8LmmwJAQl/qySV+A69H1HDG7mYxG/LTZW5+ceZrrMRg1kYPewInLm82KUuys7QZBHxwDazfGSijS39PmBlnz93lfH8nDJ3TR37AP85x+RT9DhxibFJj6p8Bmzy2MSZvtwgdTyvcujRNnzdzsC8NeoQL24xnQq9uCWgToBHcafGougCl6OoNxD0cAFE/pDUJq4P3lTjhA5lkgwBPUHWHWdtgParX5jMt9MkuveI8F/ehIbu5RF6rNg9ZEgaNrZzcDh5g1j5PQu8B81uRXxCj2Bx7qVSG/vgqvo5gKaZN266Vtva+jLZjJuosX3t1qw=